# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
# Stacks detected: cicd:github-actions:.github/workflows,deps:node:.
version: 2.1

orbs:
  node: circleci/node@5.0.3
    
jobs:
  test:
    docker:
      - image: mcr.microsoft.com/playwright:v1.40.1-jammy
  
    parallelism: 2
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: ls ~/repo   
      - run: SHARD="$((${CIRCLE_NODE_INDEX}+1))"; USERNAME=qa.datta@gmail.com PASSWORD=Test@123  xargs npm run test-ui-c -- --shard=${SHARD}/${CIRCLE_NODE_TOTAL}
      - store_test_results:
          path: ./playwright-report                        
      - store_test_results:
          path: ./test-results                        
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      # Replace this with steps to build a package, or executable
      - run:
          name: Build an artifact
          command: echo "some text" > example.txt
      - store_artifacts:
          path: example.txt

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      # Replace this with steps to deploy to users
      - run:
          name: deploy
          command: '#e.g. ./deploy.sh'
      - run:
          name: found github actions config
          command: ':'
workflows:
  example:
    jobs:
      - test
      - build:
          requires:
            - test
